### ISSUE TITLE
But.. text ?

### ISSUE THREAD

**Issue by PaolinoAngeletti** [zagum/Android-SwitchIcon#10]
Hi, but if i want text into button, i've to insert text as image ????

**Comment by zagum** [comment]
Hi, library name is SwitchIcon, so it is used only to modify your icon image view.
If you want text somewhere - combine SwitchIconView with TextView, like in sample project

**Comment by PaolinoAngeletti** [comment]
thanks. excuse me for the unesfull issue,.. in the sample was the solution. thanks.
