### ISSUE TITLE
SwitchIconView.java:209

### ISSUE THREAD

**Issue by gameplanet** [zagum/Android-SwitchIcon#14]
There is an ANR for Android 9.0

java.lang.IllegalArgumentException
Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

android.graphics.Canvas.checkValidClipOp (Canvas.java:779)
android.graphics.Canvas.clipPath (Canvas.java:1007)
com.github.zagum.switchicon.SwitchIconView.onDraw (SwitchIconView.java:209)
android.view.View.draw (View.java:20226)
android.view.View.updateDisplayListIfDirty (View.java:19101)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.updateDisplayListIfDirty (View.java:19092)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.updateDisplayListIfDirty (View.java:19092)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.draw (View.java:20229)
android.view.View.updateDisplayListIfDirty (View.java:19101)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.updateDisplayListIfDirty (View.java:19092)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.updateDisplayListIfDirty (View.java:19092)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.updateDisplayListIfDirty (View.java:19092)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.updateDisplayListIfDirty (View.java:19092)
android.view.View.draw (View.java:19954)
android.view.ViewGroup.drawChild (ViewGroup.java:4333)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
android.view.View.draw (View.java:20229)
com.android.internal.policy.DecorView.draw (DecorView.java:792)
android.view.View.updateDisplayListIfDirty (View.java:19101)
android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:686)
android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:692)
android.view.ThreadedRenderer.draw (ThreadedRenderer.java:801)
android.view.ViewRootImpl.draw (ViewRootImpl.java:3332)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3129)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2498)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1473)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7215)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1004)
android.view.Choreographer.doCallbacks (Choreographer.java:816)
android.view.Choreographer.doFrame (Choreographer.java:751)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:990)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:280)
android.app.ActivityThread.main (ActivityThread.java:6710)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

**Comment by zagum** [comment]
Hi! Do you use the latest version? 
this bug was fixed here https://github.com/zagum/Android-SwitchIcon/pull/12
