### ISSUE TITLE
Saving an original color of icon

### ISSUE THREAD

**Issue by justtwago** [zagum/Android-SwitchIcon#6]
Can I save original colors of icon?
For example this ![rsz_1rsz_1rsz_1rsz_1rsz_1rsz_11](https://cloud.githubusercontent.com/assets/16563318/24048902/98321b1a-0b2a-11e7-97c0-bb8242277e37.png)

**Comment by zagum** [comment]
No. This library supports only single-color icons, like in Material Design guides.
