### ISSUE TITLE
Wrong R.styleable attribute used to initialise SwitchIconView.enabled

### ISSUE THREAD

**Issue by andymstone** [zagum/Android-SwitchIcon#7]
In the SwitchIconView constructor, line 91 of SwitchIconView.java reads:
```
 enabled = array.getBoolean(R.styleable.SwitchIconView_si_disabled_alpha, true);
```

Shouldn't that be `R.styleable.si_enabled`?

**Comment by zagum** [comment]
Yes, this is bug. Thanks!)
Fixed in v.1.3.4
